### ISSUE TITLE
Crashes my Team Explorer pane

### ISSUE THREAD

**Issue by brettjacobson** [kemmis/Kemmis.MyWorkItemsOnPendingChangesPage#1]
The extension causes an exception to show up under the Team Explorer pane.
![capture](https://cloud.githubusercontent.com/assets/8862834/16203443/f52601e4-36df-11e6-8d00-d94a12f063a9.PNG)
Happened with 1.0.1 and still with 1.0.2

**Comment by kemmis** [comment]
Thanks for the report Brett. Could you tell me what version of Visual Studio you are using?

**Comment by brettjacobson** [comment]
VS2015 Update 2
Version 14.0.25123.00 Update 2

**Comment by kemmis** [comment]
Looks like the same issue has been reported for other vs extensions. See this page for possible work-arounds: http://diffallfilesvisualstudioextension.codeplex.com/workitem/1

@brettjacobson Anything else you might be able to tell me about your setup? Do you have other versions of visual studio installed? Is your VS 2015 the Community, Professional, or Enterprise version? What version of Windows are you running?

**Comment by brettjacobson** [comment]
VS2015 Enterprise Update 2
Yes, there is still a copy of VS2013 Update 4 ultimate installed on my machine
Windows 8.1
our TFS server is TFS 2015 Update 2

after re-installing 1.0.3 I'm getting this error on VS startup
![image](https://cloud.githubusercontent.com/assets/8862834/16242025/258bbd48-37b6-11e6-8ce7-344c59fb008e.png)

which is what I think you were expecting me to see.

That .dll is NOT in the extensions folder with the other TFS dlls in the MyWOrkItemsOnPendingChanges extension folder.  Not sure if its _supposed_ to be there or not.  There are 12 Microsoft.TeamFoundation.\* dlls in that folder.

**Comment by kemmis** [comment]
That's strange. You're saying that there is no Microsoft.TeamFoundation.Client.dll file in the folder for the MyWorkItemsOnPendingCHangesPage extension folder? It's definitely in the extension package and gets put in that folder for me. Can you double-check?

So far the common thread I've found for people having this issue is that they have an older version of Visual Studio installed along side of VS 2015. I think perhaps there's a dll from the older version of VS sneaking in somewhere. One of my coworkers is having the same issue with the extension so I'm going to try to get his help diagnosing the problem.

**Comment by brettjacobson** [comment]
I misread; I thought KnownCapFlagsScc was a dll.  Hopefully since a coworker is experiencing it it will be easier for you to diagnose!  The popup indicates it was looking in the VS2015 dll though (v14.0), definitely a strange problem!

**Comment by deadlydog** [comment]
The fix for this for my [Diff All Files VS extension](https://visualstudiogallery.msdn.microsoft.com/e6390f80-c953-4896-bd93-a7dfeba9887b) seemed to be to still include the Microsoft.*.dll files, but change Specific Version from True to False in the reference properties. Here's [the commit with the change](https://diffallfilesvisualstudioextension.codeplex.com/SourceControl/changeset/fcf47d1a9f68bbb3c1e6dd80f34ea9db5724dc0b#VS.DiffAllFiles.VS2015/VS.DiffAllFiles.VS2015.csproj) that seems to have solved the problem for my VS extension. Not sure if you have the exact same problem or not, but hopefully it will help.

A temporary workaround a user found for my problem until I could push a new version of my extension was to go into the VS extensions directory and delete the Microsoft.*.dll files I included with the extension (e.g. C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\hnqnv3ez.ahu).

**Comment by brettjacobson** [comment]
I've since installed VS2015 Enterprise Update 3, and reinstalled the extension.  Still doesn't work.
I tried deleting Microsoft.TeamFoundation._.dll and Microsoft.VisualStudio._ (separately) as suggested by @deadlydog but still no luck.

This is the exception I get on my Team Explorer pane now, which I think is still the same exception I originally experienced.

```
System.ArgumentException: Cannot create an instance of System.Collections.Generic.List`1[System.Lazy`2[Microsoft.TeamFoundation.Controls.WinForms.IPermission,Microsoft.TeamFoundation.Controls.Avatars.AvatarImageCache`1[T]]] because Type.ContainsGenericParameters is true.
   at System.RuntimeType.CreateInstanceCheckThis()
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.SatisfyImmediateImports()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by kemmis** [comment]
Brett, would you mind trying this build for me? 

https://www.dropbox.com/s/978txnr8jqbvgqf/Kemmis.MyWorkItemsOnPendingChangesPage.vsix?dl=0

**Comment by brettjacobson** [comment]
@kemmis no luck.  No exception, though.  My Team explorer pane just says "offline" and the busy indicator bar just flashes (I waited nearly 4 minutes before giving up).
![image](https://cloud.githubusercontent.com/assets/8862834/16730296/c01a89e4-4737-11e6-9d74-d9421ef0c890.png)

**Comment by kemmis** [comment]
Brett,  I ran across this tool that clears the MEF cache in Visual Studio: http://vsixgallery.com/extension/f5028141-9dd0-4ac4-ae6d-0481ae9a940d/

It essentially clears this folder for you:  %localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache

It might be worth trying to clear this folder and then install the extension again. Evidently mef cache corruption can cause various exceptions and failures in Visual Studio.

**Comment by brettjacobson** [comment]
No luck :disappointed: I tried both the dropbox version from last week and the official 1.0.3 version.  The dropbox version behaved exactly the same (just says offline and the indicator revolves).
1.0.3 did NOT show an exception in the pane, but only 3 of the typical 10 items showed up.

**Comment by kemmis** [comment]
Damn that's too bad. I'm out of ideas at this point. If you want to live on the wild side, you're welcome to use Visual Studio 15 Preview 3 with the latest version of the extension I packed with all version 15 binaries: https://visualstudiogallery.msdn.microsoft.com/7a121f25-d15e-4ea1-9e5b-8b83351ca466

I've been using VS 15 for a while now and it doesn't seem to have that many flaws. It's always just a time investment installing and updating versions of vs... one I don't mind doing every so often.

I'm going to put this issue in the parking lot and we can revisit it if either of us comes up with ideas or a solution we want to try.

Thanks!

**Comment by jit4peace** [comment]
I faced same issue after installing ShelvesetComparer tool VS2015U3. I tried to repair VS2015, but did not work.

Tried installing the provided MEF cache clearing tool and it helped me get rid of this issue.

Thank you very much for this.
