### ISSUE TITLE
System.TypeLoadException: Method 'CreateItem' in type 'Microsoft.TeamFoundation.VersionControl.Controls.PendingChanges.PendingChangesFileListViewHelper' from assembly 'Microsoft.TeamFoundation.VersionControl.Controls, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.

### ISSUE THREAD

**Issue by kemmis** [kemmis/Kemmis.MyWorkItemsOnPendingChangesPage#3]
I'm currently getting this exception in VS 2015 Update 3 - it may be because I messed up my VS dlls by hand, but I'm just logging this here in case anyone else runs into it.

> System.TypeLoadException: Method 'CreateItem' in type 'Microsoft.TeamFoundation.VersionControl.Controls.PendingChanges.PendingChangesFileListViewHelper' from assembly 'Microsoft.TeamFoundation.VersionControl.Controls, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
>    at Microsoft.TeamFoundation.VersionControl.Controls.PendingChanges.PendingChangesModel..ctor(IPendingChangesDataProvider dataProvider)
>    at Microsoft.VisualStudio.TeamFoundation.VersionControl.PendingChanges.PendingChangesModelVS..ctor(IPendingChangesDataProvider dataProvider)
>    at Microsoft.VisualStudio.TeamFoundation.VersionControl.PendingChanges.PendingChangesModelVS.CreateStaticPendingChangesModelVS()
>    at Microsoft.VisualStudio.TeamFoundation.VersionControl.PendingChanges.PendingChangesPageVS.CreateModel(PageInitializeEventArgs e)
>    at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerPageBase.Initialize(Object sender, PageInitializeEventArgs e)
>    at Microsoft.VisualStudio.TeamFoundation.VersionControl.PendingChanges.PendingChangesPageVS.Initialize(Object sender, PageInitializeEventArgs e)
>    at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerPageHost.Initialize(TeamExplorerPageContext context)

**Comment by kemmis** [comment]
This problem was due to my own stupidity of jacking up my VS installation. Closing out.
